/**
 * Etichette italiane per id colonna (picker Colonne, fallback filtri).
 * Chiavi = accessorKey / id TanStack.
 */
export const COLUMN_LABELS: Record<string, string> = {
	id: "ID",
	taxCode: "Codice fiscale",
	name: "Nome",
	surname: "Cognome",
	birthDate: "Data di nascita",
	street: "Via",
	houseNumber: "Civico",
	city: "Città",
	province: "Provincia",
	phoneNumber: "Telefono",
	email: "Email",
	enrollmentDate: "Data iscrizione",
	date: "Data",
	amount: "Importo",
	type: "Tipo",
	product: "Prodotto",
	productCode: "Codice prodotto",
	price: "Prezzo",
	year: "Anno",
	duration: "Durata (giorni)",
	numberOfEntrances: "Numero ingressi",
	clientId: "ID Cliente",
	employeeId: "ID Dipendente",
	employee: "Dipendente",
	username: "Nome utente",
	password: "Password",
	role: "Ruolo",
	approved: "Approvato",
	contractType: "Tipo contratto",
	hourlyFee: "Compenso orario",
	startingDate: "Data inizio",
	endingDate: "Data fine",
	entranceTime: "Entrata",
	exitTime: "Uscita",
	description: "Descrizione",
	provider: "Fornitore",
	maker: "Produttore",
	startingTime: "Ora inizio",
	endingTime: "Ora fine",
	saleId: "ID Vendita",
	catalogYear: "Anno listino",
	residualEntrances: "Ingressi residui",
	remainingEntrances: "Ingressi rimanenti",
	productKind: "Tipo prodotto",
	code: "Codice",
	client: "Cliente",
	entranceNumber: "Numero ingressi",
	hiringDate: "Data assunzione",
	kind: "Tipo",
	detail: "Dettagli",
	active: "Stato",
	paymentAmount: "Importo pagamento",
	paymentDate: "Data pagamento",
	paymentId: "ID Pagamento",
	address: "Indirizzo",
	contact: "Contatto",
};

export function columnLabel(columnId: string): string {
	return COLUMN_LABELS[columnId] ?? columnId;
}
