import {
	AlignLeft,
	AtSign,
	BadgeCheck,
	Ban,
	Banknote,
	BookOpen,
	BriefcaseBusiness,
	Building2,
	Calendar,
	CirclePlay,
	Clock,
	DoorOpen,
	Dumbbell,
	FileText,
	Funnel,
	HandCoins,
	HardHat,
	Hash,
	Hourglass,
	IdCard,
	KeyRound,
	LayoutDashboard,
	LogIn,
	LogOut,
	Mail,
	MapPin,
	Minus,
	Package,
	Shield,
	ShoppingBag,
	ShoppingCart,
	Tag,
	Ticket,
	Timer,
	UserCog,
	UserRound,
	Wallet,
	Wrench,
	Zap,
	type LucideIcon,
} from "lucide-react";

/**
 * Icone canoniche per entità di dominio (CONTEXT.md).
 * Una icona = una entità. Non riusare questi glyph per attributi o altre entità.
 * Eccezione: celle tipo (`DotBadge`) riusano il glifo quando il tipo è quella entità
 * (kind prodotto, tipo pagamento). Ruolo e tipo contratto hanno glifi propri in `visual.ts`.
 */
export const ENTITY_ICON = {
	overview: LayoutDashboard,
	account: UserCog,
	employee: BriefcaseBusiness,
	contract: FileText,
	clocking: Clock,
	salary: HandCoins,
	equipment: Dumbbell,
	bill: Zap,
	intervention: Wrench,
	client: UserRound,
	entrance: DoorOpen,
	product: ShoppingBag,
	membership: Ticket,
	entranceSet: Package,
	catalog: BookOpen,
	payment: Wallet,
	sale: ShoppingCart,
} as const satisfies Record<string, LucideIcon>;

export const NAV_ENTITY_ICON: Record<string, LucideIcon> = {
	"/": ENTITY_ICON.overview,
	"/accounts": ENTITY_ICON.account,
	"/employees": ENTITY_ICON.employee,
	"/contracts": ENTITY_ICON.contract,
	"/clockings": ENTITY_ICON.clocking,
	"/salaries": ENTITY_ICON.salary,
	"/equipment": ENTITY_ICON.equipment,
	"/bills": ENTITY_ICON.bill,
	"/interventions": ENTITY_ICON.intervention,
	"/clients": ENTITY_ICON.client,
	"/entrances": ENTITY_ICON.entrance,
	"/products": ENTITY_ICON.product,
	"/memberships": ENTITY_ICON.membership,
	"/entrance-sets": ENTITY_ICON.entranceSet,
	"/catalogs": ENTITY_ICON.catalog,
	"/payments": ENTITY_ICON.payment,
	"/sales": ENTITY_ICON.sale,
};

/**
 * Icone di attributo / stato. Non coincidono con ENTITY_ICON.
 */
export const ATTR_ICON = {
	id: Hash,
	date: Calendar,
	amount: Banknote,
	type: Tag,
	description: AlignLeft,
	duration: Timer,
	username: AtSign,
	password: KeyRound,
	role: Shield,
	approved: BadgeCheck,
	pending: Hourglass,
	taxCode: IdCard,
	address: MapPin,
	contact: Mail,
	clockIn: LogIn,
	clockOut: LogOut,
	inProgress: CirclePlay,
	remainingEmpty: Minus,
	remainingExhausted: Ban,
	provider: Building2,
	maker: HardHat,
	filter: Funnel,
} as const satisfies Record<string, LucideIcon>;
